development:
    adapter: postgresql
    database: confirmefacil_devel
    username: postgres
    password: postgres
    host: localhost

# Banco de teste. Nao confie em salvar nada aqui
test:
    adapter: postgresql
    database: confirmefacil_test
    username: postgres
    password: postgres
    host: 127.0.0.1

production:
    adapter: postgresql
    database: ateixeira1
    username: ateixeira1
    password: uanauana
    host: pgsql.ateixeira.com.br
